# Generated by Django 4.2.18 on 2025-03-11 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_bookinstance_options_remove_author_borrower_and_more'),
    ]

    operations = [
    ]
